### ISSUE TITLE
Settings redesign

### ISSUE THREAD

**Issue by axel358** [axel358/smartdock#133]
## Todo
- [x] Replace checkbox preference with switch preference
- [x] Replace numeric EditText Dialogs with Slider preference 
- [x] Hide dock layout preference from the app bar
- [x] Improve preference names and descriptions
- [x] Remove obsolete preferences 
- [x] About page icons 
- [x] #89
- [x] Fix pin button description 
### New preferences
- [x] Disable launcher 3 taskbar
