### ISSUE TITLE
1.12.0

### ISSUE THREAD

**Issue by axel358** [axel358/smartdock#95]
## Todo
- [x] #96
- [x] #127
- [x] #98
- [x] #99
- [x] #100
- [x] #133
- [x] Handle position preference 
- [x] Allow selection of screen on which to launch apps in
- [x] #105 
- [x] #101
- [x] #85 
- [x] Remove unused assets 
- [x] Update translations
